In [8]:
import sqlite3 as sql
import pandas as pd
from sqlalchemy import create_engine
import datetime
import geopandas as gpd
from shapely.geometry import Point
import shapely.wkt
import psycopg2

### 1. What is the general trend in sales prices by census tract over the last 10 years? In which areas of Davidson County are sales prices increasing at the highest rate? Census tract is contained in the tract column of the properties table.

In [9]:
# connect to Postgres 'housing' Database
db_name = 'housing'
connection_string = f"postgresql://postgres:postgres@localhost:5432/{db_name}"
engine = create_engine(connection_string)

In [10]:
# connect to 'census' Database
conn = sql.connect('/home/nhac/Documents/NSS/Python/projects/partnerProject2/data/census.sqlite')
cur = conn.cursor()

In [11]:
# query all tables in CENSUS db
cur.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;") 
all_tables = (cur.fetchall())

In [12]:
# View list of tables from CENSUS db
#all_tables

In [13]:
# median household income table, B19013
med_income_df = pd.read_sql("SELECT * FROM B19013;", conn)

In [14]:
trim_med_income = med_income_df[['GEO_ID','tract','value','year']]

### HOUSING DB

In [15]:
# function to get table names quickly
def get_table(tablename):
    query = f'''
        SELECT * 
        FROM {tablename}
    '''
    return pd.read_sql(query, con = engine)

In [ ]:
# get tables from database to dataframes
housing_details_df = get_table('details')
housing_ass_df = get_table('assessment')
housing_loc_df = get_table('locations')
housing_props_df = get_table('properties')
housing_sales_df = get_table('sales')

,objectid,stanpar,featuretype,parceltype,floornumber,parid,apn,dateest,isactive,dateinact,...,ludesc,landappr,imprappr,totlappr,landassd,imprassd,totlassd,assessdate,propfraction,starea
0,145,00100000100,ACREAGE TRACT,101,,61,00100000100,1965-09-15,Y,None,...,VACANT RURAL LAND,13169.0,0.0,13169.0,3292.0,0.0,3292.0,2021-01-01,None,3.734754e+05
1,146,00100000200,ACREAGE TRACT,101,,63,00100000200,1972-01-06,Y,None,...,VACANT RURAL LAND,20239.0,0.0,20239.0,5060.0,0.0,5060.0,2021-01-01,None,3.848893e+05
2,511716,00100000300,ROBERTSON,101,,393970,00100000300,1987-08-14,Y,None,...,VACANT RURAL LAND,31000.0,0.0,31000.0,0.0,0.0,0.0,2021-01-01,None,7.581112e+04
3,2,00200004700,ROBERTSON,101,,38,00200004700,1975-01-01,Y,None,...,VACANT RURAL LAND,11700.0,0.0,11700.0,0.0,0.0,0.0,2021-01-01,None,2.166646e+04
4,5,00200004900,ROBERTSON,101,,41,00200004900,1949-10-29,Y,None,...,SINGLE FAMILY,37400.0,220900.0,258300.0,0.0,0.0,0.0,2021-01-01,None,1.103852e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273308,1990743,188100J20400CO,CONDO,102,F-3,459009,188100J20400CO,2021-12-09,Y,None,...,VACANT RESIDENTIAL LAND,40000.0,0.0,40000.0,10000.0,0.0,10000.0,2022-01-01,None,1.156504e+03
273309,1964167,188100J90000CO,COMMON,101,,458999,188100J90000CO,2021-12-09,Y,None,...,VACANT RESIDENTIAL LAND,40000.0,0.0,40000.0,0.0,0.0,0.0,2022-01-01,B,7.666723e+03
273310,187681,19000000200,WILLIAMSON,101,,299147,19000000200,1979-10-24,Y,None,...,VACANT RURAL LAND,35800.0,0.0,35800.0,0.0,0.0,0.0,2021-01-01,None,1.756288e+05
273311,187682,19000000400,ACREAGE TRACT,101,,299548,19000000400,1999-11-10,Y,None,...,VACANT RURAL LAND,72720.0,0.0,72720.0,18180.0,0.0,18180.0,2021-01-01,None,1.691598e+06
273312,187683,19000000300,WILLIAMSON,101,,299148,19000000300,1951-09-05,Y,None,...,VACANT RURAL LAND,44900.0,0.0,44900.0,0.0,0.0,0.0,2021-01-01,None,2.341193e+05

In [40]:
props_2_df = housing_props_df[['apn','tract']]

In [41]:
props_2_df.to_csv('props_2.csv')

In [11]:
# trim Sales table down to selected columns, to Dataframe
trim_sales_df = housing_sales_df[['apn','saleamount','ownername','status','ownerdate']]

In [12]:
# trim Properties table down to selected columns, to Dataframe
trim_props_df = housing_props_df[['apn','tract','parceltype','saleprice','ludesc','assessdate','propzip','owner']]

In [13]:
# clean Properties DF of NaNs and 0.0s

In [14]:
temp_prop_sale = trim_props_df.dropna()

In [15]:
temp_prop_sale = trim_props_df.loc[(trim_props_df['saleprice'] > 0)]

In [16]:
# clean Sales DF of NaNs and 0.0s

In [17]:
trim_sales_df = trim_sales_df.loc[(trim_sales_df['saleamount']!=0.0)]

In [18]:
trim_sales_df = trim_sales_df.dropna()

In [19]:
# Convert 'ownerdate' column to DateTime

In [20]:
trim_sales_df.ownerdate = pd.to_datetime(trim_sales_df.ownerdate)

In [21]:
# Filter for years 2012 and above

In [22]:
trim_sales_df = trim_sales_df[(trim_sales_df['ownerdate'] >= "2010-01-01") & (trim_sales_df['ownerdate'] <= "2020-12-31")]

In [23]:
# Create a copy of trimmed sales to test with.
temp_sales_df = trim_sales_df

In [24]:
# Use copy to build merged table of Sales and Properties.
prop_sales_merge = temp_sales_df.merge(trim_props_df, left_on='apn', right_on='apn')

In [25]:
##prop_sales_merge

In [26]:
# Count relevant residential sales properties by property description
count_desc = prop_sales_merge.value_counts('ludesc')

In [27]:
# Expand max of displayed items to 100
pd.set_option('display.max_rows', 100)

In [28]:
# Create dataframe to view counts of property types
count_desc = count_desc.to_frame()

In [29]:
# Better view of property types
count_desc.reset_index()

                                           ludesc       0
0                                   SINGLE FAMILY  133089
1                               RESIDENTIAL CONDO   68418
2                         VACANT RESIDENTIAL LAND    5771
3                                   ZERO LOT LINE    4397
4                                          DUPLEX    3896
5                          VACANT COMMERCIAL LAND    1791
6                               VACANT RURAL LAND    1297
7                OFFICE BLDG (ONE OR TWO STORIES)    1171
8                                     PARKING LOT     726
9          APARTMENT: LOW RISE (BUILT SINCE 1960)     570
10             CONDOMINIUM OFC OR OTHER COM CONDO     553
11                                SMALL WAREHOUSE     485
12                 ONE STORY GENERAL RETAIL STORE     454
13                 TERMINAL/DISTRIBUTION WARHOUSE     373
14                          STRIP SHOPPING CENTER     359
15                            RESTURANT/CAFETERIA     298
16                                        TRIPLEX     244
17                          AUTO REPAIR/BODY SHOP     241
18    APARTMENT: HIGH RISE (3 STORIES OR GREATER)     227
19                         VACANT RESIENTIAL LAND     223
20                                    HOTEL/MOTEL     222
21                         RESIDENTIAL COMBO/MISC     216
22                                      FAST FOOD     210
23                         VACANT INDUSTRIAL LAND     204
24                                    AUTO DEALER     201
25                            LIGHT MANUFACTURING     200
26            MEDICAL OFFICE (ONE OR TWO STORIES)     193
27                                         CHURCH     178
28                             SMALL SERVICE SHOP     170
29                                       QUADPLEX     153
30                OFFICE BLDG (3 OR MORE STORIES)     151
31                    CONVENIENCE MARKET WITH GAS     143
32                                    MOBILE HOME     130
33                            FARM BUILDINGS ONLY     129
34                      VACANT ZONED MULTI FAMILY      95
35                                 MINI WAREHOUSE      84
36                               NIGHTCLUB/LOUNGE      80
37                                BUSINESS CENTER      79
38                                    RURAL COMBO      74
39                   BRANCH FINANCIAL INSTITUTION      65
40                                SHOPPING CENTER      63
41                                DAY CARE CENTER      62
42                                   OPEN STORAGE      56
43                               RECORDING STUDIO      52
44                                       CAR WASH      50
45                              SCHOOL OR COLLEGE      50
46                            HEAVY MANUFACTURING      50
47                       DORMITORY/BOARDING HOUSE      49
48                                   NURSING HOME      47
49  APARTMENT: WALK UP (BUILT PRIOR TO 1960)\r\nA      44
50                 CONVENIENCE MARKET WITHOUT GAS      37
51                                 PARKING GARAGE      37
52                            TRANSMITTING TOWERS      26
53                                   RECREATIONAL      25
54                                      MINI LUBE      25
55       NEIGHBORHOOD SUPERMARKET (FREE STANDING)      24
56                          CLUB/UNION HALL/LODGE      24
57                             MINERAL PROCESSING      24
58                  NON-PROFIT CHARITABLE SERVICE      21
59                               WHOLESALE OUTLET      18
60                  PACKING PLANT/FOOD PROCESSING      16
61                               MOBILE HOME PARK      14
62                            LUMBER YARD/SAWMILL      13
63      MEDICAL OFFICE (THREE STORIES OR GREATER)      11
64            CONDOMINIUM OFC  OR OTHER COM CONDO      10
65                      GOLF COURSE/DRIVING RANGE      10
66                                      PARSONAGE      10
67                              MORTUARY/CEMETERY      10
68                             THEATER/AUDITORIUM       6
69                               DEPARTMENT STORE       6
70                   SERVICE STATION FULL SERVICE       6
71                  MUSEUM OR OTHER CULTURAL ORG.       5
72                             HOSPITAL OR CLINIC       5
73                             GREENHOUSE/NURSERY       5
74                                  ENCLOSED MALL       4
75                SELF SERVICE STATION (GAS ONLY)       4
76                TERMINAL/DISTRIBUTION WAREHOUSE       3
77     METRO OTHER THAN OFC, SCHOOL,HOSP, OR PARK       3
78                                    CAMP GROUND       2
79                                    DOCK/MARINA       1
80                             PARK OR RECREATION       1

In [30]:
# Filter for potential residential properties, by property type (ludesc column)
prop_sales_res  = prop_sales_merge.loc[prop_sales_merge["ludesc"].isin(['SINGLE FAMILY', 'MOBILE HOME', 'RESIDENTIAL CONDO', 'DUPLEX', 'TRIPLEX', 'QUADPLEX'])]

In [31]:
prop_sales_res

,apn,saleamount,ownername,status,ownerdate,tract,parceltype,saleprice,ludesc,assessdate,propzip,owner
1,00200004500,272500.0,"HARP, MEGAN & SPENCER",Historical,2019-12-09,37010202,101,393000.0,SINGLE FAMILY,2021-01-01,37072,"HUNTER, ELLEN"
2,00200004500,29000.0,"COX, DOUG & GRETCHEN",Historical,2019-02-28,37010202,101,393000.0,SINGLE FAMILY,2021-01-01,37072,"HUNTER, ELLEN"
3,00200004500,29000.0,"COX, DOUG & GRETCHEN",Historical,2019-02-28,37010202,101,393000.0,SINGLE FAMILY,2021-01-01,37072,"HUNTER, ELLEN"
7,00200002700,165000.0,"LYNN, JERRY & CAROLYN",Historical,2020-05-08,37010202,101,440000.0,SINGLE FAMILY,2021-01-01,37072,"BOSTICK, JENNIFFER I & TRAYMAINE V"
9,00200003200,151000.0,"PURVIS, BRIAN & RIZZA BADUA",Current,2015-05-11,37010202,101,151000.0,SINGLE FAMILY,2021-01-01,37072,"PURVIS, BRIAN & RIZZA BADUA"
...,...,...,...,...,...,...,...,...,...,...,...,...
229314,082140A06000CO,267000.0,"BOWEN, ANDREW C.",Current,2019-03-01,37019400,102,267000.0,RESIDENTIAL CONDO,2021-01-01,37201,"BOWEN, ANDREW C."
229315,082140A06000CO,145000.0,"SHERRELL, KEN & TAMRA",Historical,2014-10-24,37019400,102,267000.0,RESIDENTIAL CONDO,2021-01-01,37201,"BOWEN, ANDREW C."
229316,082140A06000CO,113000.0,"FMBC INVESTMENTS, LLC",Historical,2012-06-07,37019400,102,267000.0,RESIDENTIAL CONDO,2021-01-01,37201,"BOWEN, ANDREW C."
229317,091092E00200CO,175000.0,"WILLMS HOME IMPROVEMENT, LLC",Historical,2018-03-08,37013202,101,0.0,RESIDENTIAL CONDO,2021-01-01,37209,"WILLMS, KURT M & ASHLEY G"
229318,13316005900,142000.0,"CANNON, ALEXANDRIA Z.",Current,2014-12-23,37019005,101,142000.0,SINGLE FAMILY,2021-01-01,37211,"CANNON, ALEXANDRIA Z."

In [32]:
housing_loc_df

,apn,geometry,centroid
0,135100C00100CO,"((-86.6550922601566,36.08968968469921),(-86.65...","(-86.6550153261827,36.08953410265812)"
1,135100C00200CO,"((-86.6547412785098,36.08936111487425),(-86.65...","(-86.65481490085843,36.089489774922804)"
2,135100C00300CO,"((-86.6543636849112,36.08949942079647),(-86.65...","(-86.65453122326811,36.089413458773656)"
3,00100000100,"((-86.89915572979601,36.389976312811555),(-86....","(-86.89974455957591,36.38885243003944)"
4,00100000200,"((-86.89848433634678,36.38997195899868),(-86.8...","(-86.89740393976102,36.388928987061355)"
...,...,...,...
273308,188100J20400CO,"((-86.61198310002041,35.98321296503606),(-86.6...","(-86.61190244581086,35.983206189691145)"
273309,188100J90000CO,"((-86.61195049887014,35.983545839303645),(-86....","(-86.61194146134004,35.98335033332511)"
273310,19000000200,"((-86.61877418466817,35.97225264255917),(-86.6...","(-86.61964564312106,35.97195474443825)"
273311,19000000400,"((-86.6142052748536,35.97036401642557),(-86.61...","(-86.61687454399375,35.96972230741119)"
273312,19000000300,"((-86.62057593167529,35.971567026101255),(-86....","(-86.62235500462279,35.972015244192214)"

In [33]:
#prop_sales_loc = prop_sales_res.merge(housing_loc_df, left_on='apn', right_on='apn')

In [34]:
#prop_sales_loc.to_csv('prop_sales_loc.csv')

In [35]:
#housing_loc_df.to_csv('')